# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iR8FYePGV7whtWGx8lS9M6snIy4UAArG
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Ensure output directory for charts exists
os.makedirs("visualizations", exist_ok=True)

print("--- STEP 1: GENERATING SYNTHETIC PHARMA SALES DATA ---")
np.random.seed(42)
data_size = 1200

# Generating realistic pharmaceutical distribution data
data = pd.DataFrame({
    'Drug_ID': np.random.randint(101, 110, size=data_size),        # 9 distinct medicine types
    'Region_ID': np.random.randint(1, 6, size=data_size),          # 5 distribution zones
    'Temperature_Sensitivity': np.random.choice([0, 1], size=data_size, p=[0.7, 0.3]), # 1 = Needs cold chain storage
    'Previous_Month_Sales': np.random.randint(500, 6000, size=data_size)
})

# Create a realistic target variable with baseline dependency and natural variance
data['Current_Month_Demand'] = (data['Previous_Month_Sales'] * 1.08) + \
                               (data['Temperature_Sensitivity'] * 150) + \
                               np.random.normal(0, 150, data_size)

# 1. SHOW THE DATA IS WORKING: Print structural confirmation
print(f"Dataset successfully created! Shape: {data.shape}\n")
print("First 5 rows of the active dataset:")
print(data.head(), "\n")

print("--- STEP 2: PREPARED DATA SPLIT ---")
X = data[['Drug_ID', 'Region_ID', 'Temperature_Sensitivity', 'Previous_Month_Sales']]
y = data['Current_Month_Demand']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}\n")

print("--- STEP 3: MODEL TRAINING (RANDOM FOREST REGRESSOR) ---")
model = RandomForestRegressor(n_estimators=150, random_state=42, max_depth=10)
model.fit(X_train, y_train)
print("Model training complete.\n")

print("--- STEP 4: GENERATING VERIFIED METRICS ---")
predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, predictions)

print(f"=== FINAL EVALUATION METRICS ===")
print(f"Mean Absolute Error (MAE) : {mae:.2f} units")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} units")
print(f"R-squared Score (R²)          : {r2 * 100:.2f}%\n")

print("--- STEP 5: VISUAL PROOF GENERATION ---")
# Chart 1: Actual vs Predicted Values
plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_test, y=predictions, alpha=0.6, color='teal')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.title('PharmaDemand-AI: Actual vs Predicted Monthly Demand')
plt.xlabel('Actual Sales (Units)')
plt.ylabel('Predicted Demand (Units)')
plt.grid(True, linestyle='--', alpha=0.5)
plt.savefig('visualizations/actual_vs_predicted.png', dpi=300)
plt.close()

# Chart 2: Feature Importance Tracking
importances = model.feature_importances_
features = X.columns
indices = np.argsort(importances)

plt.figure(figsize=(8, 5))
plt.title('Feature Importances in Demand Forecasting')
plt.barh(range(len(indices)), importances[indices], color='cornflowerblue', align='center')
plt.yticks(range(len(indices)), [features[i] for i in indices])
plt.xlabel('Relative Importance Weight')
plt.tight_layout()
plt.savefig('visualizations/feature_importance.png', dpi=300)
plt.close()

print("Visualizations successfully saved inside the 'visualizations/' directory!")
print("Everything is working smoothly.")

